kafka:
  clusters:
    - name: local
      bootstrapServers: broker:29092
      schemaRegistry: http://schema-registry:8081
      schemaRegistryAuth:
        username: superUser
        password: superUser
      metrics:
        port: 9997
        type: JMX
